language: node_js
before_install:
  - git clone --depth=50 https://github.com/kodeklubben/oppgaver.git ../oppgaver
cache: yarn
script:
  - yarn run eslint
  - yarn run stylelint
  - yarn run test
  - ./travis_build_prod.sh
  - yarn run test:links
